#!/bin/bash
# Get mining status and generate status report
# Run this script on the VPS as root

set -e

MINER_DIR="/root/midnight-miner"
WALLETS_FILE="$MINER_DIR/wallets.json"
CHALLENGES_FILE="$MINER_DIR/challenges.json"

echo "# Mining Status Report"
echo ""
echo "**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
echo "**Hostname:** $(hostname)"
echo ""

# Service status
echo "## Service Status"
echo ""
if systemctl is-active --quiet midnight-miner; then
    echo "**Status:** Running ✅"
    UPTIME=$(systemctl show midnight-miner --property=ActiveEnterTimestamp --value)
    echo "**Started:** $UPTIME"
else
    echo "**Status:** Stopped ❌"
fi
echo ""

# Hash rate from recent logs
echo "## Mining Performance"
echo ""
LAST_HASHRATE=$(journalctl -u midnight-miner -n 100 | grep "Total Hash Rate" | tail -1 | awk '{print $NF}')
if [ -n "$LAST_HASHRATE" ]; then
    echo "**Hash Rate:** $LAST_HASHRATE"
else
    echo "**Hash Rate:** N/A"
fi
echo ""

# Solutions count
SOLUTIONS_COUNT=$(journalctl -u midnight-miner | grep -c "Solution accepted" || echo "0")
echo "**Total Solutions:** $SOLUTIONS_COUNT"
echo ""

# Wallets information
echo "## Wallets"
echo ""
if [ -f "$WALLETS_FILE" ]; then
    WALLET_COUNT=$(python3 -c "import json; data=json.load(open('$WALLETS_FILE')); print(len(data))" 2>/dev/null || echo "0")
    echo "**Total Wallets:** $WALLET_COUNT"
    echo ""

    # Solutions per wallet
    echo "### Solutions per Wallet"
    echo ""
    echo "| Wallet | Address | Solutions |"
    echo "|--------|---------|-----------|"

    python3 << PYEOF
import json
import subprocess

with open('/root/midnight-miner/wallets.json') as f:
    wallets = json.load(f)

for i, wallet in enumerate(wallets):
    addr = wallet['address']
    # Count solutions for this address from logs
    result = subprocess.run(
        ['journalctl', '-u', 'midnight-miner', '--grep', addr],
        capture_output=True, text=True
    )
    solution_count = result.stdout.count('Solution accepted')

    print(f"| {i+1} | {addr[:20]}... | {solution_count} |")
PYEOF
else
    echo "No wallets file found"
fi
echo ""

# Recent solutions
echo "## Recent Solutions (Last 10)"
echo ""
RECENT_SOLUTIONS=$(journalctl -u midnight-miner | grep "Solution accepted" | tail -10)
if [ -n "$RECENT_SOLUTIONS" ]; then
    echo '```'
    echo "$RECENT_SOLUTIONS"
    echo '```'
else
    echo "No solutions found yet"
fi
echo ""

# Challenge information
echo "## Challenges"
echo ""
if [ -f "$CHALLENGES_FILE" ]; then
    python3 -c "
import json
from datetime import datetime, timezone

with open('/root/midnight-miner/challenges.json') as f:
    challenges = json.load(f)

print(f'**Total Challenges Discovered:** {len(challenges)}')
print()
print('| Challenge ID | Difficulty | Deadline |')
print('|--------------|-----------|----------|')

for cid, data in sorted(challenges.items()):
    deadline = data['latest_submission']
    diff = data['difficulty'][:8]
    print(f'| {cid} | {diff} | {deadline} |')
" 2>/dev/null || echo "Error reading challenges"
else
    echo "No challenges file found"
fi
echo ""

# System resources
echo "## System Resources"
echo ""
echo "**CPU Usage:**"
echo '```'
top -bn1 | grep "Cpu(s)" | head -1
echo '```'
echo ""
echo "**Memory Usage:**"
echo '```'
free -h | grep -E "Mem|Swap"
echo '```'
echo ""

echo "---"
echo "*Report generated by midnight-miner*"
